### ISSUE TITLE
Doesn't compile with ghc-9.2.2

### ISSUE THREAD

**Issue by henrylaxen** [snapframework/heist#134]
Dear Heist Angels,

I'm afraid I have some bad news:

 > ghc --version
 The Glorious Glasgow Haskell Compilation System, version 9.2.2
 > cabal --version
 cabal-install version 3.6.2.0
 compiled using version 3.6.2.0 of the Cabal library
 > cabal install --lib  --allow-newer  heist
....
eventually errors with:

```

src/Heist/Splices/Json.hs:100:44: error:
    • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
                     with: Map.HashMap Text Value
      Expected: Map.HashMap Text Value
        Actual: Object
    • In the second argument of ‘Map.lookup’, namely ‘obj’
      In the expression: Map.lookup x obj
      In an equation for ‘findIn’: findIn (Object obj) = Map.lookup x obj
    |
100 |         findIn (Object obj) = Map.lookup x obj
    |                                            ^^^

src/Heist/Splices/Json.hs:165:30: error:
    • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
                     with: Map.HashMap Text Value
      Expected: Map.HashMap Text Value
        Actual: Object
    • In the first argument of ‘goObject’, namely ‘o’
      In the expression: goObject o
      In an equation for ‘go’: go (Object o) = goObject o
    |
165 |     go (Object o) = goObject o
    |                              ^

```

I hope this isn't too hard to fix.  It is preventing me from upgrading to ghc-9.2
Best wishes,
Henry Laxen

**Comment by srid** [comment]
I believe https://github.com/snapframework/heist/pull/132 fixes this. But heist appears not to be maintained anymore (cf. https://github.com/snapframework/heist/pull/130#issuecomment-1086931247)

**Comment by cydparser** [comment]
The next release will include the fix.
